// Modellliste für den Viewer.
// Schlüssel = Dateiname in /modelle (ohne .glb).
// Optional: info (Text zum ganzen Modell), teile (Untermenü; id = Gruppenname im Modell;
//           detail = eigene Gruppe, die statt des Teils groß gezeigt wird),
//           hintergrund (Themenbild aus /hintergruende, Standard: blaupause),
//           abdeckung ({ id, name } – abnehmbares Teil mit eigenem Knopf, Standard: Dach),
//           ganz: false (kein „Ganzes Modell“, erster Teil wird gezeigt), animation (Clipname, auch je Teil).
//
// Einordnung (für die Übersicht, beliebig erweiterbar):
//   fach: 'Biologie' · jahrgang: [5, 6] · thema: 'Zelle' · schulform: ['HS', 'RS', 'GY']
//   schlagworte: ['Organellen', …] · kurz: ein Satz für die Karte · vorschau: false (nicht in der Übersicht)
export const SCHULFORMEN = { HS: 'Hauptschule', RS: 'Realschule', GY: 'Gymnasium' };
const ALLE = ['HS', 'RS', 'GY'];

export const MODELLE = {
  zahnrad: { name: 'Zahnradgetriebe', fach: 'Technik', jahrgang: [7, 8], thema: 'Getriebe', schulform: ALLE,
    schlagworte: ['Zahnrad', 'Übersetzung', 'Maschinen'], kurz: 'Zwei Zahnräder mit Übersetzung 2 : 1.' },
  magnet: { name: 'Stabmagnet mit Feldlinien', fach: 'Physik', jahrgang: [7], thema: 'Magnetismus', schulform: ALLE,
    schlagworte: ['Magnetfeld', 'Nordpol', 'Südpol', 'Feldlinien'], kurz: 'Räumliches Magnetfeld eines Stabmagneten.' },
  ikosaeder: { name: 'Ikosaeder', fach: 'Mathematik', jahrgang: [9], thema: 'Körper', schulform: ALLE,
    schlagworte: ['Platonische Körper', 'Geometrie', 'Kanten', 'Flächen'], kurz: 'Platonischer Körper aus 20 gleichseitigen Dreiecken.' },
  villa: {
    name: 'Römische Villa (Stadthaus)',
    fach: 'Geschichte', jahrgang: [6], thema: 'Römer', schulform: ALLE,
    schlagworte: ['Antike', 'Pompeji', 'Wohnen', 'Atrium', 'Domus'], kurz: 'Puppenhaus-Ansicht eines römischen Hauses, Räume einzeln wählbar.',
    hintergrund: 'pompeji',
    ganz: 'Ganze Villa',
    info: 'So wohnte eine reiche Familie in einer römischen Stadt wie Pompeji. Von der Straße aus sieht das Haus fast fensterlos aus – das Leben spielte sich innen ab, rund um Atrium und Garten. Wähle unten einen Raum aus!',
    teile: [
      { id: 'fauces', name: 'Fauces – Eingang',
        info: 'Durch diesen schmalen Flur betrat man das Haus von der Straße aus. Oft lag hier ein Mosaik mit einem Wachhund und der Warnung „Cave canem“ – Hüte dich vor dem Hund!' },
      { id: 'atrium', name: 'Atrium – Empfangshalle',
        info: 'Der wichtigste Raum des Hauses. Durch eine Öffnung im Dach (Compluvium) fiel Licht herein und Regenwasser in das Becken (Impluvium). Morgens empfing der Hausherr hier Besucher. Am Hausaltar (Lararium) wurden die Schutzgötter der Familie verehrt.' },
      { id: 'cubicula', name: 'Cubicula – Schlafzimmer',
        info: 'Kleine, meist fensterlose Schlafzimmer rund um das Atrium. Darin standen nur ein Bett, eine Truhe für Kleidung und vielleicht ein Hocker.' },
      { id: 'latrina', name: 'Latrina – Toilette',
        info: 'Man saß auf einer Steinbank mit Löchern, darunter floss das Abwasser weg. Toilettenpapier gab es nicht – stattdessen einen Schwamm an einem Stock, der in der Wasserrinne ausgewaschen wurde.' },
      { id: 'tablinum', name: 'Tablinum – Arbeitszimmer',
        info: 'Hier arbeitete der Hausherr (pater familias). Im Schrank lagen Schriftrollen und wichtige Dokumente. Vom Tablinum aus konnte man vom Atrium bis in den Garten blicken.' },
      { id: 'triclinium', name: 'Triclinium – Speisezimmer',
        info: 'Die Römer aßen im Liegen! Drei Liegen standen im U um einen kleinen Tisch – daher der Name (tri = drei). Beim Gastmahl gab es viele Gänge, Diener trugen die Speisen auf.' },
      { id: 'culina', name: 'Culina – Küche',
        info: 'Gekocht wurde auf einem gemauerten Herd über offenem Feuer. In Amphoren lagerten Öl, Wein und die beliebte Fischsoße Garum. Meist arbeiteten hier Sklavinnen und Sklaven.' },
      { id: 'peristyl', name: 'Peristyl – Garten',
        info: 'Ein Garten, umgeben von einem Säulengang. Hier wuchsen Kräuter, Blumen und Obstbäume, ein Brunnen plätscherte, Statuen schmückten die Beete. Ein ruhiger Ort zum Erholen.' },
      { id: 'tabernae', name: 'Tabernae – Läden',
        info: 'Läden an der Straßenseite, oft vom Hausbesitzer vermietet. Links ein Weinladen mit Theke und eingelassenen Vorratsgefäßen, rechts eine Bäckerei mit Backofen und Getreidemühle.' },
    ],
  },
  zelle56: {
    name: 'Pflanzenzelle (Kl. 5–6)',
    fach: 'Biologie', jahrgang: [5, 6], thema: 'Zelle', schulform: ALLE,
    schlagworte: ['Zellwand', 'Zellkern', 'Chloroplasten', 'Vakuole', 'Mikroskopie'], kurz: 'Aufgeschnittene Blattzelle mit den Grundbausteinen.',
    hintergrund: 'blatt',
    ganz: 'Ganze Zelle',
    abdeckung: { id: 'vorderseite', name: 'Hülle schließen' },
    info: 'Pflanzen bestehen aus vielen winzigen Zellen – eine Blattzelle ist nur etwa 0,05 mm groß. Die Zelle ist oben und vorne aufgeschnitten, damit du hineinschauen kannst. Wähle unten einen Zellbestandteil!',
    teile: [
      { id: 'zellwand', name: 'Zellwand',
        info: 'Eine feste Hülle aus Zellulose. Sie gibt der Pflanzenzelle ihre Form und macht sie stabil – ähnlich wie ein Karton. Tierzellen haben keine Zellwand.' },
      { id: 'zellmembran', name: 'Zellmembran',
        info: 'Ein hauchdünnes Häutchen direkt innen an der Zellwand. Es bestimmt, welche Stoffe in die Zelle hinein- und aus ihr hinausgelangen.' },
      { id: 'zellplasma', name: 'Zellplasma',
        info: 'Eine zähflüssige Masse, die die Zelle ausfüllt. Darin liegen alle anderen Zellbestandteile, und hier laufen viele Lebensvorgänge ab.' },
      { id: 'zellkern', name: 'Zellkern',
        info: 'Die Steuerzentrale der Zelle. Er enthält die Erbinformation und bestimmt, was in der Zelle passiert. Im Inneren liegt das dunkle Kernkörperchen.' },
      { id: 'vakuole', name: 'Vakuole',
        info: 'Ein großer Speicherraum voller Zellsaft (Wasser mit gelösten Stoffen). Ist sie prall gefüllt, drückt sie von innen gegen die Zellwand – so bleibt die Pflanze straff. Fehlt Wasser, welkt die Pflanze.' },
      { id: 'chloroplasten', detail: 'chloroplasten_detail', name: 'Chloroplasten (Blattgrünkörner)',
        info: 'Hier stellt die Pflanze mithilfe von Licht aus Wasser und Kohlenstoffdioxid Zucker her – die Fotosynthese. Dabei entsteht Sauerstoff. Innen liegen gestapelte grüne Scheibchen mit dem Blattgrün (Chlorophyll).' },
    ],
  },
  zelle78: {
    name: 'Pflanzenzelle (Kl. 7–8)',
    fach: 'Biologie', jahrgang: [7, 8], thema: 'Zelle', schulform: ALLE,
    schlagworte: ['Organellen', 'Mitochondrien', 'ER', 'Golgi', 'Ribosomen', 'Fotosynthese'], kurz: 'Blattzelle mit allen Organellen, Einzelansichten mit Innenleben.',
    hintergrund: 'blatt',
    ganz: 'Ganze Zelle',
    abdeckung: { id: 'vorderseite', name: 'Hülle schließen' },
    info: 'Schnitt durch eine Blattzelle (Palisadengewebe), etwa 0,05 mm groß. Kern, Chloroplasten und Mitochondrien sind aufgeschnitten, damit du ihren inneren Aufbau siehst. Wähle unten ein Zellorganell!',
    teile: [
      { id: 'zellwand', name: 'Zellwand',
        info: 'Besteht vor allem aus Zellulosefasern. Sie ist fest, aber für Wasser und gelöste Stoffe durchlässig, und verhindert, dass die Zelle bei hohem Innendruck (Turgor) platzt.' },
      { id: 'tuepfel', detail: 'tuepfel_detail', name: 'Tüpfel',
        info: 'Dünne Stellen in der Zellwand. Durch feine Plasmastränge (Plasmodesmen) sind benachbarte Zellen miteinander verbunden und können Stoffe austauschen.' },
      { id: 'zellmembran', name: 'Zellmembran',
        info: 'Eine Doppelschicht aus Lipiden mit eingelagerten Proteinen. Sie ist selektiv permeabel: Bestimmte Stoffe lässt sie durch, andere nicht.' },
      { id: 'zellplasma', name: 'Cytoplasma',
        info: 'Wässrige Grundsubstanz mit gelösten Salzen, Zuckern und Proteinen. Darin liegen die Organellen; viele Stoffwechselreaktionen laufen hier ab.' },
      { id: 'zellkern', name: 'Zellkern (Nucleus)',
        info: 'Enthält die Erbinformation (DNA) als Chromatin. Die Kernhülle ist eine Doppelmembran mit Kernporen, durch die z. B. Bauanleitungen für Proteine (mRNA) ins Plasma gelangen. Im Kernkörperchen (Nucleolus) entstehen Bausteine der Ribosomen.' },
      { id: 'vakuole', name: 'Vakuole',
        info: 'Von einer eigenen Membran (Tonoplast) umgeben und mit Zellsaft gefüllt. Speichert Wasser, Nähr-, Farb- und Abfallstoffe. Ihr Druck auf die Zellwand (Turgor) stabilisiert die Pflanze.' },
      { id: 'chloroplasten', detail: 'chloroplasten_detail', name: 'Chloroplasten',
        info: 'Ort der Fotosynthese: 6 CO₂ + 6 H₂O → C₆H₁₂O₆ + 6 O₂ (mit Lichtenergie). Außen eine Doppelmembran, innen gestapelte Thylakoide (Grana) mit Chlorophyll, dazwischen die Grundsubstanz (Stroma).' },
      { id: 'mitochondrien', detail: 'mitochondrien_detail', name: 'Mitochondrien',
        info: 'Die „Kraftwerke“ der Zelle: Bei der Zellatmung wird Zucker mithilfe von Sauerstoff abgebaut, dabei wird Energie für die Zelle frei. Die innere Membran ist stark gefaltet (Cristae) – so entsteht mehr Oberfläche.' },
      { id: 'er', name: 'Endoplasmatisches Retikulum (ER)',
        info: 'Ein Netz aus Membransäcken und -röhren. Das raue ER ist mit Ribosomen besetzt und stellt Proteine her; das glatte ER bildet u. a. Fette (Lipide) und dient dem Stofftransport.' },
      { id: 'golgi', name: 'Golgi-Apparat',
        info: 'Ein Stapel flacher Membransäckchen. Er verändert und verpackt Stoffe (z. B. Proteine) und verschickt sie in kleinen Bläschen (Vesikeln) – die Poststelle der Zelle.' },
      { id: 'ribosomen', detail: 'ribosomen_detail', name: 'Ribosomen',
        info: 'Winzige Körnchen, an denen Proteine zusammengebaut werden. Sie liegen frei im Cytoplasma oder sitzen auf dem rauen ER.' },
    ],
  },
  plattentektonik: {
    name: 'Plattentektonik (Kl. 6)',
    fach: 'Erdkunde', jahrgang: [6], thema: 'Plattentektonik', schulform: ALLE,
    schlagworte: ['Erdaufbau', 'Vulkan', 'Erdbeben', 'Gebirgsbildung', 'Animation'], kurz: 'Fünf animierte Blockbilder: Erdaufbau und Plattenbewegungen.',
    ganz: false,
    info: 'Zeitraffer: Was hier in Sekunden passiert, dauert in Wirklichkeit Millionen Jahre. Die Platten bewegen sich nur wenige Zentimeter pro Jahr – etwa so schnell, wie deine Fingernägel wachsen.',
    teile: [
      { id: 'erde', animation: 'erde', name: 'Aufbau der Erde',
        info: 'Die Erde ist aufgebaut wie ein Pfirsich: Außen liegt die dünne, feste Erdkruste. Darunter folgt der heiße, zähflüssige Erdmantel (bis 2900 km tief). Innen liegt der Erdkern – außen flüssig, innen fest und über 5000 °C heiß. Die Kruste ist in große Platten zerbrochen. Die kreisenden Punkte zeigen die langsamen Strömungen im Mantel, die die Platten antreiben.' },
      { id: 'divergenz', animation: 'divergenz', name: 'Auseinanderdriften',
        info: 'Zwei Platten bewegen sich voneinander weg. In den Spalt steigt glühendes Magma aus dem Erdmantel auf. Es erstarrt zu neuem Meeresboden, in der Mitte entsteht ein Gebirge unter Wasser (Mittelozeanischer Rücken). So ist der Atlantik entstanden – er wird jedes Jahr etwa 2 cm breiter. Island liegt genau auf so einer Naht.' },
      { id: 'subduktion', animation: 'subduktion', name: 'Abtauchen',
        info: 'Die schwere Ozeanplatte schiebt sich unter die leichtere Kontinentplatte und taucht in den Erdmantel ab. Dort entsteht ein tiefer Graben im Meer. In der Tiefe schmilzt Gestein, das Magma steigt auf und bildet Vulkane. Weil sich die Platten dabei verhaken, gibt es hier oft Erdbeben. Beispiel: die Anden in Südamerika.' },
      { id: 'kollision', animation: 'kollision', name: 'Zusammenstoßen',
        info: 'Zwei Kontinentplatten stoßen zusammen. Keine taucht ab – das Gestein wird zusammengeschoben, gefaltet und in die Höhe gedrückt: Ein Faltengebirge entsteht. Beispiel: der Himalaya mit dem Mount Everest. Auch die Alpen sind so entstanden. Der Himalaya wächst noch heute.' },
      { id: 'transform', animation: 'transform', name: 'Aneinander vorbeischieben',
        info: 'Zwei Platten gleiten seitlich aneinander vorbei. Oft verhaken sie sich, und es baut sich Spannung auf – bis sie sich plötzlich ruckartig lösen: ein Erdbeben! Achte auf die Straße und den Zaun. Beispiel: der San-Andreas-Graben in Kalifornien.' },
    ],
  },
  viertaktmotor: {
    name: 'Viertakt-Ottomotor',
    fach: 'Technik', jahrgang: [8, 9], thema: 'Verbrennungsmotor', schulform: ALLE,
    schlagworte: ['Ottomotor', 'Kolben', 'Kurbelwelle', 'Ventile', 'Energieumwandlung', 'Animation'],
    kurz: 'Aufgeschnittener Motor: das Arbeitsspiel in vier Takten, jeder Takt einzeln abspielbar.',
    ganz: false,
    info: 'Der Motor ist aufgeschnitten, damit du hineinsehen kannst.',
    teile: [
      { id: 'gesamt', detail: 'motor', animation: 'viertakt', name: 'Gesamtablauf (4 Takte)',
        info: 'Der Ottomotor wandelt die chemische Energie des Benzins in Bewegungsenergie um. Ein Arbeitsspiel hat vier Takte und dauert zwei Umdrehungen der Kurbelwelle (gelbe Markierung am Schwungrad). Die Nockenwellen oben drehen sich dabei nur einmal – sie öffnen und schließen die Ventile im richtigen Moment.' },
      { id: 'ansaugen', detail: 'motor', animation: 'ansaugen', name: '1. Takt: Ansaugen',
        info: 'Der Kolben bewegt sich nach unten, das Einlassventil (links) ist geöffnet. Dadurch wird ein Gemisch aus Luft und fein verteiltem Benzin (blau) in den Zylinder gesaugt.' },
      { id: 'verdichten', detail: 'motor', animation: 'verdichten', name: '2. Takt: Verdichten',
        info: 'Beide Ventile sind geschlossen. Der Kolben bewegt sich nach oben und presst das Gemisch auf einen kleinen Teil seines Volumens zusammen (violett). Druck und Temperatur steigen stark an.' },
      { id: 'arbeiten', detail: 'motor', animation: 'arbeiten', name: '3. Takt: Arbeiten',
        info: 'Kurz bevor der Kolben ganz oben ist, zündet die Zündkerze das Gemisch. Es verbrennt blitzschnell, die heißen Gase dehnen sich aus und drücken den Kolben kräftig nach unten (roter Pfeil). Nur in diesem Takt wird Arbeit verrichtet – das schwere Schwungrad hält den Motor in den anderen drei Takten in Bewegung.' },
      { id: 'ausstossen', detail: 'motor', animation: 'ausstossen', name: '4. Takt: Ausstoßen',
        info: 'Das Auslassventil (rechts) öffnet sich. Der Kolben bewegt sich wieder nach oben und schiebt die verbrannten Abgase (grau-braun) durch den Auspuffkrümmer hinaus. Danach beginnt alles von vorn.' },
    ],
  },
};
