// Modellliste für den Viewer.
// Schlüssel = Dateiname in /modelle (ohne .glb).
// Optional: info (Text zum ganzen Modell), teile (Untermenü; id = Gruppenname im Modell;
//           detail = eigene Gruppe, die statt des Teils groß gezeigt wird),
//           thema (Hintergrundbild aus /hintergruende, Standard: blaupause),
//           abdeckung ({ id, name } – abnehmbares Teil mit eigenem Knopf, Standard: Dach).
export const MODELLE = {
  zahnrad: { name: 'Zahnradgetriebe' },
  magnet: { name: 'Stabmagnet mit Feldlinien' },
  ikosaeder: { name: 'Ikosaeder' },
  villa: {
    name: 'Römische Villa (Stadthaus)',
    thema: 'pompeji',
    ganz: 'Ganze Villa',
    info: 'So wohnte eine reiche Familie in einer römischen Stadt wie Pompeji. Von der Straße aus sieht das Haus fast fensterlos aus – das Leben spielte sich innen ab, rund um Atrium und Garten. Wähle unten einen Raum aus!',
    teile: [
      { id: 'fauces', name: 'Fauces – Eingang',
        info: 'Durch diesen schmalen Flur betrat man das Haus von der Straße aus. Oft lag hier ein Mosaik mit einem Wachhund und der Warnung „Cave canem“ – Hüte dich vor dem Hund!' },
      { id: 'atrium', name: 'Atrium – Empfangshalle',
        info: 'Der wichtigste Raum des Hauses. Durch eine Öffnung im Dach (Compluvium) fiel Licht herein und Regenwasser in das Becken (Impluvium). Morgens empfing der Hausherr hier Besucher. Am Hausaltar (Lararium) wurden die Schutzgötter der Familie verehrt.' },
      { id: 'cubicula', name: 'Cubicula – Schlafzimmer',
        info: 'Kleine, meist fensterlose Schlafzimmer rund um das Atrium. Darin standen nur ein Bett, eine Truhe für Kleidung und vielleicht ein Hocker.' },
      { id: 'latrina', name: 'Latrina – Toilette',
        info: 'Man saß auf einer Steinbank mit Löchern, darunter floss das Abwasser weg. Toilettenpapier gab es nicht – stattdessen einen Schwamm an einem Stock, der in der Wasserrinne ausgewaschen wurde.' },
      { id: 'tablinum', name: 'Tablinum – Arbeitszimmer',
        info: 'Hier arbeitete der Hausherr (pater familias). Im Schrank lagen Schriftrollen und wichtige Dokumente. Vom Tablinum aus konnte man vom Atrium bis in den Garten blicken.' },
      { id: 'triclinium', name: 'Triclinium – Speisezimmer',
        info: 'Die Römer aßen im Liegen! Drei Liegen standen im U um einen kleinen Tisch – daher der Name (tri = drei). Beim Gastmahl gab es viele Gänge, Diener trugen die Speisen auf.' },
      { id: 'culina', name: 'Culina – Küche',
        info: 'Gekocht wurde auf einem gemauerten Herd über offenem Feuer. In Amphoren lagerten Öl, Wein und die beliebte Fischsoße Garum. Meist arbeiteten hier Sklavinnen und Sklaven.' },
      { id: 'peristyl', name: 'Peristyl – Garten',
        info: 'Ein Garten, umgeben von einem Säulengang. Hier wuchsen Kräuter, Blumen und Obstbäume, ein Brunnen plätscherte, Statuen schmückten die Beete. Ein ruhiger Ort zum Erholen.' },
      { id: 'tabernae', name: 'Tabernae – Läden',
        info: 'Läden an der Straßenseite, oft vom Hausbesitzer vermietet. Links ein Weinladen mit Theke und eingelassenen Vorratsgefäßen, rechts eine Bäckerei mit Backofen und Getreidemühle.' },
    ],
  },
  zelle56: {
    name: 'Pflanzenzelle (Kl. 5–6)',
    thema: 'blatt',
    ganz: 'Ganze Zelle',
    abdeckung: { id: 'vorderseite', name: 'Hülle schließen' },
    info: 'Pflanzen bestehen aus vielen winzigen Zellen – eine Blattzelle ist nur etwa 0,05 mm groß. Die Zelle ist oben und vorne aufgeschnitten, damit du hineinschauen kannst. Wähle unten einen Zellbestandteil!',
    teile: [
      { id: 'zellwand', name: 'Zellwand',
        info: 'Eine feste Hülle aus Zellulose. Sie gibt der Pflanzenzelle ihre Form und macht sie stabil – ähnlich wie ein Karton. Tierzellen haben keine Zellwand.' },
      { id: 'zellmembran', name: 'Zellmembran',
        info: 'Ein hauchdünnes Häutchen direkt innen an der Zellwand. Es bestimmt, welche Stoffe in die Zelle hinein- und aus ihr hinausgelangen.' },
      { id: 'zellplasma', name: 'Zellplasma',
        info: 'Eine zähflüssige Masse, die die Zelle ausfüllt. Darin liegen alle anderen Zellbestandteile, und hier laufen viele Lebensvorgänge ab.' },
      { id: 'zellkern', name: 'Zellkern',
        info: 'Die Steuerzentrale der Zelle. Er enthält die Erbinformation und bestimmt, was in der Zelle passiert. Im Inneren liegt das dunkle Kernkörperchen.' },
      { id: 'vakuole', name: 'Vakuole',
        info: 'Ein großer Speicherraum voller Zellsaft (Wasser mit gelösten Stoffen). Ist sie prall gefüllt, drückt sie von innen gegen die Zellwand – so bleibt die Pflanze straff. Fehlt Wasser, welkt die Pflanze.' },
      { id: 'chloroplasten', detail: 'chloroplasten_detail', name: 'Chloroplasten (Blattgrünkörner)',
        info: 'Hier stellt die Pflanze mithilfe von Licht aus Wasser und Kohlenstoffdioxid Zucker her – die Fotosynthese. Dabei entsteht Sauerstoff. Innen liegen gestapelte grüne Scheibchen mit dem Blattgrün (Chlorophyll).' },
    ],
  },
  zelle78: {
    name: 'Pflanzenzelle (Kl. 7–8)',
    thema: 'blatt',
    ganz: 'Ganze Zelle',
    abdeckung: { id: 'vorderseite', name: 'Hülle schließen' },
    info: 'Schnitt durch eine Blattzelle (Palisadengewebe), etwa 0,05 mm groß. Kern, Chloroplasten und Mitochondrien sind aufgeschnitten, damit du ihren inneren Aufbau siehst. Wähle unten ein Zellorganell!',
    teile: [
      { id: 'zellwand', name: 'Zellwand',
        info: 'Besteht vor allem aus Zellulosefasern. Sie ist fest, aber für Wasser und gelöste Stoffe durchlässig, und verhindert, dass die Zelle bei hohem Innendruck (Turgor) platzt.' },
      { id: 'tuepfel', detail: 'tuepfel_detail', name: 'Tüpfel',
        info: 'Dünne Stellen in der Zellwand. Durch feine Plasmastränge (Plasmodesmen) sind benachbarte Zellen miteinander verbunden und können Stoffe austauschen.' },
      { id: 'zellmembran', name: 'Zellmembran',
        info: 'Eine Doppelschicht aus Lipiden mit eingelagerten Proteinen. Sie ist selektiv permeabel: Bestimmte Stoffe lässt sie durch, andere nicht.' },
      { id: 'zellplasma', name: 'Cytoplasma',
        info: 'Wässrige Grundsubstanz mit gelösten Salzen, Zuckern und Proteinen. Darin liegen die Organellen; viele Stoffwechselreaktionen laufen hier ab.' },
      { id: 'zellkern', name: 'Zellkern (Nucleus)',
        info: 'Enthält die Erbinformation (DNA) als Chromatin. Die Kernhülle ist eine Doppelmembran mit Kernporen, durch die z. B. Bauanleitungen für Proteine (mRNA) ins Plasma gelangen. Im Kernkörperchen (Nucleolus) entstehen Bausteine der Ribosomen.' },
      { id: 'vakuole', name: 'Vakuole',
        info: 'Von einer eigenen Membran (Tonoplast) umgeben und mit Zellsaft gefüllt. Speichert Wasser, Nähr-, Farb- und Abfallstoffe. Ihr Druck auf die Zellwand (Turgor) stabilisiert die Pflanze.' },
      { id: 'chloroplasten', detail: 'chloroplasten_detail', name: 'Chloroplasten',
        info: 'Ort der Fotosynthese: 6 CO₂ + 6 H₂O → C₆H₁₂O₆ + 6 O₂ (mit Lichtenergie). Außen eine Doppelmembran, innen gestapelte Thylakoide (Grana) mit Chlorophyll, dazwischen die Grundsubstanz (Stroma).' },
      { id: 'mitochondrien', detail: 'mitochondrien_detail', name: 'Mitochondrien',
        info: 'Die „Kraftwerke“ der Zelle: Bei der Zellatmung wird Zucker mithilfe von Sauerstoff abgebaut, dabei wird Energie für die Zelle frei. Die innere Membran ist stark gefaltet (Cristae) – so entsteht mehr Oberfläche.' },
      { id: 'er', name: 'Endoplasmatisches Retikulum (ER)',
        info: 'Ein Netz aus Membransäcken und -röhren. Das raue ER ist mit Ribosomen besetzt und stellt Proteine her; das glatte ER bildet u. a. Fette (Lipide) und dient dem Stofftransport.' },
      { id: 'golgi', name: 'Golgi-Apparat',
        info: 'Ein Stapel flacher Membransäckchen. Er verändert und verpackt Stoffe (z. B. Proteine) und verschickt sie in kleinen Bläschen (Vesikeln) – die Poststelle der Zelle.' },
      { id: 'ribosomen', detail: 'ribosomen_detail', name: 'Ribosomen',
        info: 'Winzige Körnchen, an denen Proteine zusammengebaut werden. Sie liegen frei im Cytoplasma oder sitzen auf dem rauen ER.' },
    ],
  },
};
